# Generated by Django 4.1.7 on 2023-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='deamon',
            field=models.BooleanField(default=False, verbose_name='Демонстрирующий экран'),
        ),
    ]
