# Generated by Django 4.1.7 on 2023-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conference_deamon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('T', 'Преподаватель'), ('S', 'Студент')], default='S', max_length=1, verbose_name='Роль'),
        ),
    ]
