# Generated by Django 4.1.7 on 2023-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='camera',
            field=models.BooleanField(default=False, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='conference',
            name='microphone',
            field=models.BooleanField(default=False, verbose_name='Микрофон'),
        ),
    ]
