# Generated by Django 4.1.7 on 2023-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_moviesgenerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesgenerate',
            name='movies',
            field=models.BinaryField(verbose_name='Запись'),
        ),
    ]
