# Generated by Django 4.1.7 on 2023-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_alter_moviesgenerate_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesgenerate',
            name='movies',
            field=models.TextField(verbose_name='Запись'),
        ),
    ]
