# Generated by Django 4.1.7 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_alter_moviesgenerate_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesgenerate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
